#!/usr/bin/env node
// Archivist Sprint Processor
// Processes Scout's research output and saves to wiki

const fs = require('fs');
const path = require('path');

const WIKI_DIR = '/home/n8garvie/NateMate/notes/NateMateNotes/SavedWiki';
const SPRINT_FILE = process.argv[2];

if (!SPRINT_FILE) {
  console.error('Usage: node archive-sprint.js <sprint-file.json>');
  process.exit(1);
}

function slugify(text) {
  return text.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function formatDate(dateStr) {
  const date = new Date(dateStr);
  return date.toISOString().split('T')[0];
}

function archiveIdea(idea, date) {
  const slug = slugify(idea.title);
  const filePath = path.join(WIKI_DIR, 'ideas', `${slug}.md`);
  
  // Skip if already exists
  if (fs.existsSync(filePath)) {
    console.log(`  ⏭️  Already archived: ${idea.title}`);
    return;
  }

  const content = `# ${idea.title}

**Source:** ${idea.source || 'Scout Research'}  
**Discovered:** ${date}  
**Status:** ${idea.status || 'pending'}  
**Potential:** ${idea.potential || 'medium'}

## Description
${idea.description}

## Target Audience
${idea.targetAudience}

## MVP Scope
${idea.mvpScope}

## Tags
${(idea.tags || []).map(t => `#${t}`).join(' ')}

---
*Archived by Archivist on ${date}*
`;

  fs.writeFileSync(filePath, content);
  console.log(`  ✓ Archived idea: ${idea.title}`);
}

function archiveResearchLog(sprint, date) {
  // Archive Reddit research
  if (sprint.reddit && sprint.reddit.length > 0) {
    const redditPath = path.join(WIKI_DIR, 'research', 'reddit', `research-${date}.md`);
    
    const posts = sprint.reddit.map(post => `### ${post.title}
- **Subreddit:** ${post.subreddit}
- **Upvotes:** ${post.upvotes}
- **Comments:** ${post.comments}
- **Source:** ${post.url}
`).join('\n');

    const content = `# Reddit Research - ${date}

## Posts Analyzed
${posts}

## Ideas Generated
${(sprint.ideas || []).map(i => `- ${i.title}`).join('\n')}

---
*Archived by Archivist on ${date}*
`;

    fs.writeFileSync(redditPath, content);
    console.log(`  ✓ Archived Reddit research: ${sprint.reddit.length} posts`);
  }

  // Archive Product Hunt research
  if (sprint.productHunt && sprint.productHunt.length > 0) {
    const phPath = path.join(WIKI_DIR, 'research', 'producthunt', `trending-${date}.md`);
    
    const products = sprint.productHunt.map(p => `### ${p.name}
- **Tagline:** ${p.tagline}
- **Votes:** ${p.votes}
- **Source:** ${p.url}
`).join('\n');

    const content = `# Product Hunt Trending - ${date}

## Products Analyzed
${products}

---
*Archived by Archivist on ${date}*
`;

    fs.writeFileSync(phPath, content);
    console.log(`  ✓ Archived Product Hunt research: ${sprint.productHunt.length} products`);
  }
}

function main() {
  console.log('📚 Processing sprint archive...\n');

  // Read sprint data
  const sprintData = JSON.parse(fs.readFileSync(SPRINT_FILE, 'utf-8'));
  const date = formatDate(sprintData.timestamp || new Date());

  // Create directories
  ['ideas', 'research/reddit', 'research/producthunt', 'research/hackernews'].forEach(dir => {
    fs.mkdirSync(path.join(WIKI_DIR, dir), { recursive: true });
  });

  // Archive ideas
  if (sprintData.ideas && sprintData.ideas.length > 0) {
    console.log(`Archiving ${sprintData.ideas.length} ideas...`);
    sprintData.ideas.forEach(idea => archiveIdea(idea, date));
  }

  // Archive research logs
  console.log('\nArchiving research logs...');
  archiveResearchLog(sprintData, date);

  // Update index
  const indexPath = path.join(WIKI_DIR, 'README.md');
  const indexContent = `# SavedWiki Index

Last updated: ${new Date().toISOString()}

## Recent Ideas
${(sprintData.ideas || []).slice(0, 5).map(i => `- [[${slugify(i.title)}|${i.title}]]`).join('\n')}

## Categories
- [[ideas/]] - Product ideas and concepts
- [[research/]] - Market research and analysis
- [[patterns/]] - Emerging trends and patterns

---
*Auto-generated by Archivist*
`;

  fs.writeFileSync(indexPath, indexContent);
  console.log('\n✓ Archive complete');
}

main();
