import { mutation } from "./_generated/server";

export default mutation(async ({ db }) => {
  const agents = [
    {
      name: "Atlas",
      role: "Product Manager / Squad Lead",
      emoji: "🎯",
      sessionKey: "agent:pm:main",
      status: "idle" as const,
      level: "lead" as const,
      skills: ["product", "strategy", "coordination"],
      canScout: false,
      canBuild: true,
      tasksCompleted: 0,
      ideasScouted: 0,
    },
    {
      name: "Muse",
      role: "Creative Director",
      emoji: "🎨",
      sessionKey: "agent:creative:main",
      status: "idle" as const,
      level: "lead" as const,
      skills: ["creative", "vision", "brand"],
      canScout: false,
      canBuild: true,
      tasksCompleted: 0,
      ideasScouted: 0,
    },
    {
      name: "Pixel",
      role: "UI/Visual Designer",
      emoji: "✏️",
      sessionKey: "agent:designer:main",
      status: "idle" as const,
      level: "specialist" as const,
      skills: ["design", "ui", "visual"],
      canScout: false,
      canBuild: true,
      tasksCompleted: 0,
      ideasScouted: 0,
    },
    {
      name: "Scout",
      role: "User/Market Researcher",
      emoji: "🔍",
      sessionKey: "agent:researcher:main",
      status: "idle" as const,
      level: "specialist" as const,
      skills: ["research", "analysis", "trends"],
      canScout: true,
      canBuild: false,
      tasksCompleted: 0,
      ideasScouted: 0,
    },
    {
      name: "Forge",
      role: "Tech Lead / Engineer",
      emoji: "⚡",
      sessionKey: "agent:engineer:main",
      status: "idle" as const,
      level: "lead" as const,
      skills: ["engineering", "architecture", "code"],
      canScout: false,
      canBuild: true,
      tasksCompleted: 0,
      ideasScouted: 0,
    },
    {
      name: "Lens",
      role: "QA / Usability Tester",
      emoji: "🔬",
      sessionKey: "agent:qa:main",
      status: "idle" as const,
      level: "specialist" as const,
      skills: ["qa", "testing", "usability"],
      canScout: false,
      canBuild: true,
      tasksCompleted: 0,
      ideasScouted: 0,
    },
    {
      name: "Echo",
      role: "Copywriter / Content Designer",
      emoji: "✍️",
      sessionKey: "agent:copy:main",
      status: "idle" as const,
      level: "specialist" as const,
      skills: ["copy", "content", "messaging"],
      canScout: false,
      canBuild: true,
      tasksCompleted: 0,
      ideasScouted: 0,
    },
    {
      name: "Amp",
      role: "Marketer",
      emoji: "📣",
      sessionKey: "agent:marketing:main",
      status: "idle" as const,
      level: "specialist" as const,
      skills: ["marketing", "growth", "launch"],
      canScout: false,
      canBuild: true,
      tasksCompleted: 0,
      ideasScouted: 0,
    },
  ];

  for (const agent of agents) {
    await db.insert("agents", agent);
  }

  return { message: "Agents seeded successfully", count: agents.length };
});
