#!/bin/bash
# post-build-screenshot.sh - Standard post-build screenshot automation for Mission Control
# This script is called automatically after every successful build
# It captures a screenshot of the running app and adds it to the README

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}📸 Mission Control: Post-Build Screenshot${NC}"
echo "=========================================="

# Check if we're in a project directory with a build
if [ ! -f "package.json" ]; then
    echo -e "${YELLOW}⚠️  No package.json found, skipping screenshot${NC}"
    exit 0
fi

# Check if README exists
if [ ! -f "README.md" ]; then
    echo -e "${YELLOW}⚠️  No README.md found, creating one...${NC}"
    PROJECT_NAME=$(basename $(pwd))
    echo "# ${PROJECT_NAME}" > README.md
    echo "" >> README.md
    echo "Generated by Mission Control" >> README.md
fi

# Determine project type and port
PORT=3000
if grep -q '"next"' package.json 2>/dev/null; then
    echo -e "${BLUE}📦 Detected: Next.js project${NC}"
    START_CMD="npm run dev"
    BUILD_CMD="npm run build"
elif grep -q '"vite"' package.json 2>/dev/null; then
    echo -e "${BLUE}📦 Detected: Vite project${NC}"
    START_CMD="npm run dev"
    PORT=5173
elif grep -q '"react-scripts"' package.json 2>/dev/null; then
    echo -e "${BLUE}📦 Detected: Create React App${NC}"
    START_CMD="npm start"
    PORT=3000
else
    echo -e "${BLUE}📦 Generic Node.js project${NC}"
    START_CMD="npm start"
fi

# Build first (for static screenshot)
echo -e "${BLUE}🔨 Building project...${NC}"
if ! $BUILD_CMD 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Build failed or not available, will try dev server${NC}"
fi

# Find available port
echo -e "${BLUE}🔍 Finding available port...${NC}"
for try_port in $PORT 3001 3002 3003 3004 3005 5173 5174 8080; do
    if ! lsof -Pi :$try_port -sTCP:LISTEN -t >/dev/null 2>&1; then
        PORT=$try_port
        echo -e "${GREEN}✓ Using port: $PORT${NC}"
        break
    fi
done

# Start dev server in background
echo -e "${BLUE}🚀 Starting dev server on port $PORT...${NC}"
$START_CMD -- --port $PORT &
SERVER_PID=$!

# Wait for server to be ready
echo -e "${BLUE}⏳ Waiting for server...${NC}"
for i in {1..60}; do
    if curl -s http://localhost:$PORT > /dev/null 2>&1; then
        echo -e "${GREEN}✓ Server ready!${NC}"
        break
    fi
    sleep 1
done

# Check if playwright is available
if ! command -v npx &> /dev/null; then
    echo -e "${RED}❌ npx not found, cannot capture screenshot${NC}"
    kill $SERVER_PID 2>/dev/null || true
    exit 1
fi

# Capture screenshot
echo -e "${BLUE}📷 Capturing screenshot...${NC}"
SCREENSHOT_NAME="screenshot.png"

if npx playwright screenshot \
    --full-page \
    --wait-for-timeout 5000 \
    --color-scheme=dark \
    "http://localhost:$PORT" \
    "$SCREENSHOT_NAME" 2>/dev/null; then
    
    echo -e "${GREEN}✓ Screenshot saved: $SCREENSHOT_NAME${NC}"
    
    # Add to README if not already present
    if ! grep -q "screenshot.png" README.md; then
        echo -e "${BLUE}📝 Adding screenshot to README...${NC}"
        
        # Create temp file with screenshot added after title
        awk -v screenshot="\n![App Screenshot](./screenshot.png)\n" '
            /^# / && !added {
                print
                print screenshot
                added = 1
                next
            }
            { print }
        ' README.md > README.md.tmp
        
        mv README.md.tmp README.md
        echo -e "${GREEN}✓ Screenshot added to README${NC}"
    fi
    
    # Git operations
    if [ -d ".git" ]; then
        echo -e "${BLUE}📤 Committing to Git...${NC}"
        git add README.md $SCREENSHOT_NAME 2>/dev/null || true
        git commit -m "Add screenshot to README [Mission Control]" 2>/dev/null || true
        echo -e "${GREEN}✓ Committed${NC}"
    fi
    
else
    echo -e "${RED}❌ Screenshot capture failed${NC}"
fi

# Cleanup
echo -e "${BLUE}🛑 Stopping dev server...${NC}"
kill $SERVER_PID 2>/dev/null || true
wait $SERVER_PID 2>/dev/null || true

echo ""
echo -e "${GREEN}✅ Post-build screenshot complete!${NC}"
