#!/bin/bash
# Create minimal working apps for empty Mission Control repos

set -e

REPOS_DIR="/tmp/fix-empty-repos-$$"
mkdir -p "$REPOS_DIR"
cd "$REPOS_DIR"

# Define repos and their descriptions
declare -A REPO_DESCRIPTIONS=(
  ["gitflow-intelligence"]="AI-powered GitHub issue analyzer that automatically reproduces bugs, suggests fixes, and creates detailed reproduction steps"
  ["homeserver-wizard"]="Guided setup tool for self-hosting beginners that creates custom installation scripts and configs"
  ["agentwatch-dashboard"]="Clean monitoring interface for developers running multiple AI coding agents"
  ["memory-consolidator-ai"]="AI-powered knowledge base that automatically merges similar notes and removes outdated information"
  ["ai-memory-stack"]="Self-hosted memory layer for AI agents with smart consolidation and contradiction detection"
  ["response-helper-ai"]="AI-powered keyboard shortcut tool that suggests thoughtful responses to messages"
  ["network-pulse"]="Beautiful real-time network monitoring dashboard with smart alerting"
  ["meta-metrics"]="Privacy-focused website analytics alternative without cookie banners"
  ["smart-home-cost-optimizer"]="Analytics dashboard for smart home devices tracking energy usage"
)

echo "🔧 Creating minimal apps for empty repos..."
echo "Working directory: $REPOS_DIR"
echo ""

for repo_name in "${!REPO_DESCRIPTIONS[@]}"; do
  description="${REPO_DESCRIPTIONS[$repo_name]}"
  
  echo "========================================"
  echo "📦 Processing: $repo_name"
  echo "========================================"
  
  # Check if repo is empty (only README)
  file_count=$(gh api repos/n8garvie/$repo_name/contents/ 2>/dev/null | jq 'length' || echo "0")
  
  if [ "$file_count" -gt 1 ]; then
    echo "✅ $repo_name already has code. Skipping."
    continue
  fi
  
  echo "📝 Repo is empty. Creating minimal Next.js app..."
  
  # Clone the repo
  gh repo clone n8garvie/$repo_name 2>&1 || {
    echo "❌ Failed to clone $repo_name"
    continue
  }
  
  cd "$repo_name"
  
  # Save the original README content
  original_readme=$(cat README.md 2>/dev/null || echo "# $repo_name")
  
  # Create package.json
  cat > package.json << EOF
{
  "name": "$repo_name",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "15.2.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "typescript": "^5",
    "tailwindcss": "^4",
    "postcss": "^8"
  }
}
EOF

  # Create next.config.js
  cat > next.config.js << 'EOF'
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  distDir: 'dist'
}
module.exports = nextConfig
EOF

  # Create tsconfig.json
  cat > tsconfig.json << 'EOF'
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF

  # Create postcss.config.js
  cat > postcss.config.js << 'EOF'
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
EOF

  # Create tailwind.config.js
  cat > tailwind.config.js << 'EOF'
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
EOF

  # Create app directory structure
  mkdir -p app
  
  # Create layout.tsx
  cat > app/layout.tsx << 'EOF'
export const metadata = {
  title: 'App',
  description: 'Generated by Mission Control'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">{children}</body>
    </html>
  )
}
EOF

  # Create page.tsx with the repo content
  cat > app/page.tsx << EOF
export default function Home() {
  return (
    <main className="min-h-screen p-8 max-w-4xl mx-auto">
      <h1 className="text-4xl font-bold mb-4">${repo_name}</h1>
      <p className="text-lg text-gray-600 mb-8">${description}</p>
      
      <div className="bg-white rounded-lg shadow p-6">
        <h2 className="text-2xl font-semibold mb-4">Coming Soon</h2>
        <p className="text-gray-600">
          This project is being built by Mission Control. 
          Check back soon for updates!
        </p>
      </div>
      
      <footer className="mt-12 pt-8 border-t text-center text-gray-500">
        Built by Mission Control
      </footer>
    </main>
  )
}
EOF

  # Create .gitignore
  cat > .gitignore << 'EOF'
# Dependencies
/node_modules
/.pnp
.pnp.js

# Next.js
/.next/
/out/
/dist/

# Production
/build

# Misc
.DS_Store
*.pem
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# IDE
.idea
.vscode
*.swp
*.swo
EOF

  # Update README with the description
  cat > README.md << EOF
# ${repo_name}

${description}

## Overview

This project was generated by Mission Control.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) to view the app.
EOF

  echo "📦 Installing dependencies..."
  npm install 2>&1 | tail -3
  
  echo "🔨 Building project..."
  npm run build 2>&1 | tail -5 || echo "Build may have warnings, continuing..."
  
  # Try to capture screenshot
  echo "📸 Capturing screenshot..."
  npm run dev &
  SERVER_PID=$!
  sleep 8
  
  npx playwright screenshot --full-page --wait-for-timeout 5000 http://localhost:3000 screenshot.png 2>&1 || {
    echo "⚠️ Screenshot capture failed"
  }
  
  kill $SERVER_PID 2>/dev/null || true
  sleep 2
  
  # Add screenshot to README if captured
  if [ -f "screenshot.png" ]; then
    echo "" >> README.md
    echo "![App Screenshot](./screenshot.png)" >> README.md
    echo "✅ Screenshot added"
  fi
  
  # Commit and push
  echo "📤 Pushing to GitHub..."
  git add -A
  git commit -m "Add minimal Next.js app with screenshot [Mission Control Fix]"
  git push origin main || git push origin master
  
  echo "✅ $repo_name fixed!"
  echo ""
  
  cd "$REPOS_DIR"
done

echo "========================================"
echo "🎉 All empty repos fixed!"
echo "========================================"
