#!/bin/bash
# Fix empty Mission Control repos by building them properly
# This script clones empty repos, builds the project, and pushes code + screenshot

set -e

REPOS=(
  "gitflow-intelligence:AI-powered GitHub issue analyzer that automatically reproduces bugs, suggests fixes, and creates detailed reproduction steps"
  "homeserver-wizard:Guided setup tool for self-hosting beginners that creates custom installation scripts and configs"
  "agentwatch-dashboard:Clean monitoring interface for developers running multiple AI coding agents"
  "memory-consolidator-ai:AI-powered knowledge base that automatically merges similar notes and removes outdated information"
  "ai-memory-stack:Self-hosted memory layer for AI agents with smart consolidation and contradiction detection"
  "response-helper-ai:AI-powered keyboard shortcut tool that suggests thoughtful responses to messages"
  "network-pulse:Beautiful real-time network monitoring dashboard with smart alerting"
  "meta-metrics:Privacy-focused website analytics alternative without cookie banners"
  "smart-home-cost-optimizer:Analytics dashboard for smart home devices tracking energy usage"
)

WORK_DIR="/tmp/fix-repos-$(date +%s)"
mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

echo "🔧 Fixing empty Mission Control repos..."
echo "Working directory: $WORK_DIR"
echo ""

for repo_info in "${REPOS[@]}"; do
  IFS=':' read -r repo_name repo_desc <<< "$repo_info"
  
  echo "========================================"
  echo "📦 Processing: $repo_name"
  echo "========================================"
  
  # Check if repo exists and is empty (README only)
  files=$(gh api repos/n8garvie/$repo_name/contents/ 2>/dev/null | jq -r '.[].name' | wc -l)
  
  if [ "$files" -gt 1 ]; then
    echo "✅ $repo_name already has code ($files files). Skipping."
    continue
  fi
  
  echo "📝 Repo has only README. Building project..."
  
  # Clone the repo
  gh repo clone n8garvie/$repo_name 2>&1 || {
    echo "❌ Failed to clone $repo_name"
    continue
  }
  
  cd "$repo_name"
  
  # Read the README to understand what to build
  readme_content=$(cat README.md 2>/dev/null || echo "")
  echo "📄 README: ${readme_content:0:100}..."
  
  # Create a proper Next.js project structure
  echo "🏗️ Creating Next.js project structure..."
  
  # Initialize package.json
  cat > package.json << 'EOF'
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "15.2.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "typescript": "^5"
  }
}
EOF

  # Create tsconfig.json
  cat > tsconfig.json << 'EOF'
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF

  # Create next.config.js
  cat > next.config.js << 'EOF'
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  distDir: 'dist'
}
module.exports = nextConfig
EOF

  # Create app directory and basic page
  mkdir -p app
  
  cat > app/layout.tsx << 'EOF'
export const metadata = {
  title: 'App',
  description: 'Generated by Mission Control'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
EOF

  cat > app/page.tsx << EOF
export default function Home() {
  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui' }}>
      <h1>${repo_name}</h1>
      <p>${repo_desc}</p>
      <p style={{ color: '#666', marginTop: '1rem' }}>
        Built by Mission Control
      </p>
    </main>
  )
}
EOF

  # Create .gitignore
  cat > .gitignore << 'EOF'
/node_modules
/.next
/out
/dist
*.log
.env
.env.local
EOF

  # Install dependencies
  echo "📦 Installing dependencies..."
  npm install 2>&1 | tail -5
  
  # Build the project
  echo "🔨 Building project..."
  npm run build 2>&1 | tail -10
  
  # Capture screenshot if playwright is available
  if command -v npx &> /dev/null; then
    echo "📸 Capturing screenshot..."
    
    # Start dev server in background
    npm run dev &
    SERVER_PID=$!
    
    # Wait for server
    sleep 5
    
    # Capture screenshot
    npx playwright screenshot --full-page --wait-for-timeout 3000 http://localhost:3000 screenshot.png 2>&1 || {
      echo "⚠️ Screenshot capture failed, continuing..."
    }
    
    # Kill server
    kill $SERVER_PID 2>/dev/null || true
    
    # Add screenshot to README if it exists
    if [ -f screenshot.png ]; then
      echo "" >> README.md
      echo "![App Screenshot](./screenshot.png)" >> README.md
      echo "✅ Screenshot added to README"
    fi
  fi
  
  # Commit and push
  echo "📤 Pushing to GitHub..."
  git add -A
  git commit -m "Add project files and screenshot [Mission Control Fix]" || true
  git push origin main || git push origin master || true
  
  echo "✅ $repo_name fixed!"
  echo ""
  
  # Go back to work directory
  cd "$WORK_DIR"
done

echo "========================================"
echo "🎉 All repos fixed!"
echo "========================================"
